"""add analytics fields to notifications

Revision ID: ba5d1f9dfc12
Revises: cbb25f49ed23
Create Date: 2026-07-29 10:37:38.979366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ba5d1f9dfc12'
down_revision: Union[str, Sequence[str], None] = 'cbb25f49ed23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider', sa.String(length=100), nullable=True))
    op.add_column('notifications', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'processing_time_ms')
    op.drop_column('notifications', 'provider')
    # ### end Alembic commands ###