"""create notification reports table

Revision ID: cbb25f49ed23
Revises: 964ec9f9b628
Create Date: 2026-07-29 10:20:55.399041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cbb25f49ed23'
down_revision: Union[str, Sequence[str], None] = '964ec9f9b628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notifications_processed', sa.Integer(), nullable=False),
    sa.Column('successful_notifications', sa.Integer(), nullable=False),
    sa.Column('failed_notifications', sa.Integer(), nullable=False),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('sms_count', sa.Integer(), nullable=False),
    sa.Column('whatsapp_count', sa.Integer(), nullable=False),
    sa.Column('best_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_statistics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_reports')
    # ### end Alembic commands ###